services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=online_shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main_net
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    
  djangoonlineshop:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: djangoonlineshop
    volumes: 
      - .:/djangoonlineshop
    depends_on:
      - db
    expose:
      - "8000"
    networks:
      - main_net
    ports:
      - "8000:8000"
    restart: on-failure

volumes:
  postgres_data:

networks:
  main_net: